name: Full Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"

jobs:
  run-ci:
    runs-on: self-hosted
    steps:
     - uses: ./.github/workflows/main.yml
       with:
        upload-artifact: false
  
